version: "3.3"

services:
  core:
    container_name: core
#    env_file:
#      - ./.env
    networks:
      - core_base
#    build:
#      context: ./
#      dockerfile: Dockerfile
    depends_on:
      - redis
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: unless-stopped


  redis:
    container_name: core_redis
    image: redis:7.2.4-alpine
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    networks:
      - core_base

  postgres:
    user: "root"
    container_name: core_postgres
    image: timescale/timescaledb-ha:pg15-latest
    shm_size: 4g
    networks:
      - core_base
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata/production/data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 2s
      retries: 5
networks:
  core_base:
    name: core_base
